version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: brr
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpass
    ports:
      - "3333:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy: 
     resources:
      limits:
       cpus: "1.0"
       memory: "512M"
    restart: "always"
    networks:
      - app_net
  app:
    image: registration:latest 
    container_name: spring-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/brr
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    ports:
      - "8080:8080"
    restart: "always"
    deploy:
     resources:
       limits:
         cpus: "0.5"
         memory: "128M"
    networks:
      - app_net

volumes:
  mysql_data:
networks:
  app_net:
